-- 시스템 스키마

-- 사용자 생성
CREATE USER C##FREEBANK IDENTIFIED BY 1234;

-- CONNECT: 사용자가 DB에 접속할 수 있는 권한
-- RESOURCE: 데이터를 생성, 수정, 삭제할 수 있는 권한
GRANT CONNECT, RESOURCE TO C##FREEBANK;

-- system 에서 유저 권한 줘야 에러 없이 DB 에 저장 가능
-- QUOTA : 테이블 공간 사용
ALTER USER C##FREEBANK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--------------------------------------------------------------------------------------------
-- FREEBANK 스키마

-- 상품 테이블
CREATE TABLE FREEBANKSHOP (
    FREEBANKSHOP_ID NUMBER PRIMARY KEY,                     -- 상품 고유번호(PK)
    FREEBANKSHOP_NAME VARCHAR2(50) NOT NULL,                -- 상품명
    FREEBANKSHOP_CONTENTS VARCHAR2(255) NOT NULL,           -- 상품설명
    FREEBANKSHOP_PRICE NUMBER NOT NULL,                     -- 상품가격
    FREEBANKSHOP_ADMINID VARCHAR2(50) NOT NULL,             -- 상품관리자
    FREEBANKSHOP_CREATE DATE DEFAULT SYSDATE,               -- 상품등록일(기본값: 현재 날짜)
    FREEBANKSHOP_UPDATE DATE DEFAULT SYSDATE                -- 상품수정일 (기본값: 현재 날짜)

);

-- FREEBANKSHOP 테이블 PK 값 시퀀스 생성
CREATE SEQUENCE FREEBANKSHOP_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 회원 테이블
CREATE TABLE FREEBANKUSER (
    FREEBANKUSER_ID VARCHAR2(50) PRIMARY KEY,           -- 회원 아이디(PK)
    FREEBANKUSER_NAME VARCHAR2(50) NOT NULL,            -- 회원 이름
    FREEBANKUSER_PWD VARCHAR2(50) NOT NULL,             -- 회원 비밀번호
    FREEBANKUSER_AGE NUMBER NOT NULL,                   -- 회원 나이
    FREEBANKUSER_SEX CHAR(1),                           -- 회원 성별 (남자:'X', 여자:'Y')
    FREEBANKUSER_EMAIL VARCHAR2(50) NOT NULL,           -- 회원 이메일
    FREEBANKUSER_ADMIN CHAR(1) NOT NULL,                -- 회원 관리자 여부
    FREEBANKUSER_CREDITRATING NUMBER NOT NULL,          -- 회원 신용등급
    FREEBANKUSER_TOTAL NUMBER NOT NULL                  -- 회원 누적금액
);


-- 계좌 테이블
CREATE TABLE FREEBANKACCOUNT (
    FREEBANKACCOUNT_ACCOUNT VARCHAR2(50) PRIMARY KEY,        -- 계좌 번호(PK)
    FREEBANKACCOUNT_BALANCE NUMBER DEFAULT 0 NOT NULL,       -- 계좌 잔액 (기본값: 0)
    FREEBANKACCOUNT_CREATE DATE DEFAULT SYSDATE,             -- 계좌 생성 날짜
    FREEBANKUSER_ID VARCHAR2(50) NOT NULL,                   -- 회원 아이디(FK)
    CONSTRAINT FK_FREEBANKUSER FOREIGN KEY (FREEBANKUSER_ID) REFERENCES FREEBANKUSER(FREEBANKUSER_ID) ON DELETE CASCADE
);


--게시판 테이블
CREATE TABLE FREEBANKBOARD (
    FREEBANKBOARD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- 게시판 고유번호(PK)
    FREEBANKBOARD_TITLE VARCHAR2(255) NOT NULL,                               -- 게시판 제목
    FREEBANKBOARD_AUTHOR VARCHAR2(50) NOT NULL,                               -- 게시판 작성자
    FREEBANKBOARD_CONTENT CLOB NOT NULL,                                      -- 게시판 내용
    FREEBANKBOARD_CREATED DATE DEFAULT SYSDATE,                               -- 게시판 작성일(기본값 현재 날짜)
    FREEBANKBOARD_UPDATE DATE DEFAULT SYSDATE                                 -- 게시판 수정일(기본값 현재 날짜)
);


--구매내역 테이블
CREATE TABLE FREEBANKPURCHASELIST (
    FREEBANKPURCHASELIST_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     --구매내역 고유번호(PK)
    FREEBANKPURCHASELIST_USERID VARCHAR2(50) NOT NULL,                               --구매내역 유저아이디
    FREEBANKPURCHASELIST_ACCOUNT VARCHAR2(50) NOT NULL,                              --구매내역 계좌번호
    FREEBANKPURCHASELIST_SHOPID NUMBER NOT NULL,                                     --구매내역 상품번호
    FREEBANKPURCHASELIST_SHOPNAME VARCHAR2(50) NOT NULL,                             --구매내역 상품이름
    FREEBANKPURCHASELIST_TOTALPAYMENT NUMBER NOT NULL,                               --구매내역 총결제금액
    FREEBANKPURCHASELIST_TOTALSHOPCOUNT NUMBER NOT NULL,                             --구매내역 총상품갯수
    FREEBANKPURCHASELIST_CREATE DATE DEFAULT SYSDATE                                 --구매내역 결제날짜(기본값 현재 날짜)
);


select sum(FREEBANKPURCHASELIST_TOTALPAYMENT) 
from FREEBANKPURCHASELIST
where FREEBANKPURCHASELIST_USERID='2'
and FREEBANKPURCHASELIST_ACCOUNT = '1111111'
;

select * from FREEBANKPURCHASELIST;



