-- 시스템 스키마

-- 사용자 생성
CREATE USER C##FREEBANK IDENTIFIED BY 1234;

-- CONNECT: 사용자가 DB에 접속할 수 있는 권한
-- RESOURCE: 데이터를 생성, 수정, 삭제할 수 있는 권한
GRANT CONNECT, RESOURCE TO C##FREEBANK;

-- system 에서 유저 권한 줘야 에러 없이 DB 에 저장 가능
-- QUOTA : 테이블 공간 사용
ALTER USER C##FREEBANK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--------------------------------------------------------------------------------------------
-- FREEBANK 스키마

-- 상품 테이블
CREATE TABLE FREEBANKSHOP (
    FREEBANKSHOP_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- 상품 고유번호(PK)
    FREEBANKSHOP_NAME VARCHAR2(50) NOT NULL,                                -- 상품명
    FREEBANKSHOP_CONTENTS VARCHAR2(255) NOT NULL,                           -- 상품설명
    FREEBANKSHOP_PRICE NUMBER NOT NULL,                                     -- 상품가격
    FREEBANKSHOP_ADMINID VARCHAR2(50) NOT NULL,                             -- 상품관리자
    FREEBANKSHOP_CREATE DATE DEFAULT SYSDATE,                               -- 상품등록일(기본값: 현재 날짜)
    FREEBANKSHOP_UPDATE DATE DEFAULT SYSDATE                                
    -- 상품수정일 (기본값: 현재 날짜)
);


-- 회원 테이블
CREATE TABLE FREEBANKUSER (
    FREEBANKUSER_ID VARCHAR2(50) PRIMARY KEY,          
    FREEBANKUSER_NAME VARCHAR2(50) NOT NULL,            
    FREEBANKUSER_PWD VARCHAR2(50) NOT NULL,   
    FREEBANKUSER_AGE NUMBER NOT NULL,                                     
    FREEBANKUSER_SEX CHAR(1),
    FREEBANKUSER_EMAIL VARCHAR2(50) NOT NULL,
    FREEBANKUSER_ADMIN CHAR(1) DEFAULT 'n' NOT NULL ,                             
    FREEBANKUSER_CREDITRATING NUMBER DEFAULT 5 NOT NULL,
    FREEBANKUSER_TOTAL NUMBER DEFAULT 0 NOT NULL,
    FREEBANKUSER_CREATE DATE DEFAULT SYSDATE,
    FREEBANKUSER_UPDATE DATE DEFAULT SYSDATE
);


-- 계좌 테이블
CREATE TABLE FREEBANKACCOUNT (
    FREEBANKACCOUNT_ACCOUNT VARCHAR2(50) PRIMARY KEY,        -- 계좌 번호(PK)
    FREEBANKACCOUNT_BALANCE NUMBER DEFAULT 0 NOT NULL,       -- 계좌 잔액 (기본값: 0)
    FREEBANKACCOUNT_CREATE DATE DEFAULT SYSDATE,             -- 계좌 생성 날짜
    FREEBANKUSER_ID VARCHAR2(50) NOT NULL,                   -- 회원 아이디(FK)
    CONSTRAINT FK_FREEBANKUSER FOREIGN KEY (FREEBANKUSER_ID) REFERENCES FREEBANKUSER(FREEBANKUSER_ID) ON DELETE CASCADE
);


--게시판 테이블
CREATE TABLE FREEBANKBOARD (
    FREEBANKBOARD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- 게시판 고유번호(PK)
    FREEBANKBOARD_TITLE VARCHAR2(255) NOT NULL,                               -- 게시판 제목
    FREEBANKBOARD_AUTHOR VARCHAR2(50) NOT NULL,                               -- 게시판 작성자
    FREEBANKBOARD_CONTENT CLOB NOT NULL,                                      -- 게시판 내용
    FREEBANKBOARD_CREATED DATE DEFAULT SYSDATE,                               -- 게시판 작성일(기본값 현재 날짜)
    FREEBANKBOARD_UPDATE DATE DEFAULT SYSDATE                                 
    -- 게시판 수정일(기본값 현재 날짜)
);



--구매내역 테이블
CREATE TABLE FREEBANKPURCHASELIST (
    FREEBANKPURCHASELIST_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     --구매내역 고유번호(PK)
    FREEBANKPURCHASELIST_USERID VARCHAR2(50) NOT NULL,                               --구매내역 유저아이디
    FREEBANKPURCHASELIST_ACCOUNT VARCHAR2(50) NOT NULL,                              --구매내역 계좌번호
    FREEBANKPURCHASELIST_SHOPID NUMBER NOT NULL,                                     --구매내역 상품번호
    FREEBANKPURCHASELIST_SHOPNAME VARCHAR2(50) NOT NULL,                             --구매내역 상품이름
    FREEBANKPURCHASELIST_TOTALPAYMENT NUMBER NOT NULL,                               --구매내역 총결제금액
    FREEBANKPURCHASELIST_TOTALSHOPCOUNT NUMBER NOT NULL,                             --구매내역 총상품갯수
    FREEBANKPURCHASELIST_CREATE DATE DEFAULT SYSDATE                                 
    --구매내역 결제날짜(기본값 현재 날짜)
);

