--------------------------------------------------------
--  파일이 생성됨 - 목요일-2월-13-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CUS_DELINUM
--------------------------------------------------------

   CREATE SEQUENCE  "C##USER01"."CUS_DELINUM"  MINVALUE 100001 MAXVALUE 100100 INCREMENT BY 1 START WITH 100041 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ABC_USER
--------------------------------------------------------

  CREATE TABLE "C##USER01"."ABC_USER" 
   (	"CARDNUM" VARCHAR2(20 BYTE), 
	"COUPON" VARCHAR2(20 BYTE), 
	"U_QUEST" VARCHAR2(300 BYTE), 
	"MONEY" NUMBER, 
	"CVC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "C##USER01"."CATEGORY" 
   (	"NAME" VARCHAR2(30 BYTE), 
	"PRICE" VARCHAR2(30 BYTE), 
	"STOCK" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "C##USER01"."MEMBER" 
   (	"M_ID" VARCHAR2(50 BYTE), 
	"M_NAME" VARCHAR2(50 BYTE), 
	"M_PW" VARCHAR2(50 BYTE), 
	"M_ADDRESS" VARCHAR2(100 BYTE), 
	"M_EMAIL" VARCHAR2(100 BYTE), 
	"M_PHONENUMBER" VARCHAR2(100 BYTE), 
	"M_FRIENDID" VARCHAR2(50 BYTE), 
	"M_PWOK" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAY
--------------------------------------------------------

  CREATE TABLE "C##USER01"."PAY" 
   (	"DELIVERYNUM" NUMBER, 
	"PAYDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##USER01.ABC_USER
SET DEFINE OFF;
Insert into C##USER01.ABC_USER (CARDNUM,COUPON,U_QUEST,MONEY,CVC) values ('123456','30%',null,96667,null);
REM INSERTING into C##USER01.CATEGORY
SET DEFINE OFF;
REM INSERTING into C##USER01.MEMBER
SET DEFINE OFF;
Insert into C##USER01.MEMBER (M_ID,M_NAME,M_PW,M_ADDRESS,M_EMAIL,M_PHONENUMBER,M_FRIENDID,M_PWOK) values ('qwer','하나','1234','경기','www@qwer','010235','12345',null);
Insert into C##USER01.MEMBER (M_ID,M_NAME,M_PW,M_ADDRESS,M_EMAIL,M_PHONENUMBER,M_FRIENDID,M_PWOK) values ('gksk','서하나','1234','lkjhf','gksk@na.co','경기도','010345',null);
REM INSERTING into C##USER01.PAY
SET DEFINE OFF;
Insert into C##USER01.PAY (DELIVERYNUM,PAYDATE) values (100001,to_date('25/02/11','RR/MM/DD'));
Insert into C##USER01.PAY (DELIVERYNUM,PAYDATE) values (100003,to_date('25/02/12','RR/MM/DD'));
Insert into C##USER01.PAY (DELIVERYNUM,PAYDATE) values (100022,to_date('25/02/13','RR/MM/DD'));
Insert into C##USER01.PAY (DELIVERYNUM,PAYDATE) values (100002,to_date('25/02/11','RR/MM/DD'));
Insert into C##USER01.PAY (DELIVERYNUM,PAYDATE) values (100021,to_date('25/02/13','RR/MM/DD'));
Insert into C##USER01.PAY (DELIVERYNUM,PAYDATE) values (100023,to_date('25/02/13','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008420
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##USER01"."SYS_C008420" ON "C##USER01"."MEMBER" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "C##USER01"."MEMBER" MODIFY ("M_ID" NOT NULL ENABLE);
  ALTER TABLE "C##USER01"."MEMBER" MODIFY ("M_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##USER01"."MEMBER" MODIFY ("M_PW" NOT NULL ENABLE);
  ALTER TABLE "C##USER01"."MEMBER" MODIFY ("M_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##USER01"."MEMBER" ADD PRIMARY KEY ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAY
--------------------------------------------------------

  ALTER TABLE "C##USER01"."PAY" MODIFY ("DELIVERYNUM" NOT NULL ENABLE);
  ALTER TABLE "C##USER01"."PAY" MODIFY ("PAYDATE" NOT NULL ENABLE);
